language: java
install: true

script: ./gradlew clean build

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - sudo rm /etc/apt/sources.list.d/mysql.list
  - sudo service mysql stop
  - sudo rm -rf /var/lib/mysql
  - sudo apt-get remove apparmor
  - sudo apt-get remove --purge mysql-common mysql-community-server mysql-community-client mysql-client libmysqlclient18 libmysqlclient-dev mysql-server
  - sudo apt-get autoremove
  - sudo apt-get autoclean
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install libmysqlclient-dev libmysqlclient18 mysql-client mysql-server
  - mysql -u root -e 'create database db_book;'
  - mysql -u root -e "CREATE USER 'apiuser'@'localhost' IDENTIFIED BY 'password’"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'apiuser'@'localhost'"