language: java
install: true

jdk:
  - oraclejdk8

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.5
    - mysql-client-core-5.5
    - mysql-client-5.5

services:
  - mysql

before_install:
  - mysql -u root -e 'create database book_db;'
  - mysql -u root -e "CREATE USER 'apiuser'@'localhost' IDENTIFIED BY 'password'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'apiuser'@'localhost'"

script: ./gradlew clean build

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/